### ISSUE TITLE
It's only for two list 

### ISSUE THREAD

**Issue by braulio94** [masudias/dynamic-recyclerview#2]
What happens if I happens if want to papulate an infinit number of lists, will it crash? Even if I do end up getting it do how will the app perform? Will it consume too much data? Battery perhaps? Did you take all of this into consideration or where you just trying to solve your own problem?

**Comment by StrawHatAaron** [comment]
Good questions braulio94 I may have the answer to that soon for the third list. let me know if you are still curious.

**Comment by masudias** [comment]
@braulio94 yes, the example is showing a `RecyclerView` populating two lists only. But the idea of joining more than two lists is almost the same. I didn't provide a library rather than a code example. The code example is to tell the idea of using multiple view types for handling data from different source. So if you want to have more than two lists, then of course you can do that using different view types. 

> What happens if I happens if want to papulate an infinit number of lists, will it crash?

What do you mean by infinite number of lists? So I guess, you're planning to have a infinite scrolling behaviour like Facebook where the data is coming from so many lists. As long as you can manage those lists, of course you can have different view types for each of your lists and then populate them in your `RecyclerView`. 

> Even if I do end up getting it do how will the app perform? Will it consume too much data? Battery perhaps?

The views will be recycled hence, there's nothing to be worried about trying to populate too much data in a `RecyclerView` as long as you can manage your lists. 

Please let me know if there's any other confusions.

**Comment by e4basil** [comment]
@masudias what if  its dynamic list (sometimes 2,3,4 )

**Comment by masudias** [comment]
You need to write different adapters for handling two lists, three lists or four lists. The key idea is, you need to handle different view holders for each list if they do not have similar items. I have shown how to write different view holders based on the items found in different lists. Please let me know if you need any specific help. I will be very happy to assist.

**Comment by masudias** [comment]
I am closing this issue as I got no further questions.
